### ISSUE TITLE
DynamicObject.Edit doesn't work

### ISSUE THREAD

**Issue by ikkentim** [ikkentim/SampSharp-streamer#12]
```
public virtual void Edit(GtaPlayer player)
{
    AssertNotDisposed();

    Native.EditPlayerObject(player.Id, Id);
}
```

should use streamer's EditObject.

**Comment by ghost** [comment]
Also came across this.

Work around as of current is 
                StreamerNative.EditDynamicObject(Player.Id, Object.Id);
