### ISSUE TITLE
Setting DynamicObject.Position

### ISSUE THREAD

**Issue by Strichinger** [ikkentim/SampSharp-streamer#7]
... seems to ignore the X coordinate

**Comment by ikkentim** [comment]
Will do some testing soon.

**Comment by Strichinger** [comment]
I fixed it temporarily by using the natives

**Comment by ikkentim** [comment]
A new data type (SyncRotation) was added in streamer 2.7.7 which caused the enumerator values of X , Y and Z to change. #10 should fix this error.
