### ISSUE TITLE
Various streamer errors

### ISSUE THREAD

**Issue by Strichinger** [ikkentim/SampSharp-streamer#9]
**\* Streamer Plugin: Streamer_SetFloatData: Invalid data specified
**\* Streamer Plugin: Streamer_GetFloatData: Invalid data specified

Also, after i edit a DynamicObject as a Player, the position coordinates are invalid.

**Comment by ikkentim** [comment]
A new data type (SyncRotation) was added in streamer 2.7.7 which caused the enumerator values of X and Y to change. #10 should fix this error.
